defaultBaseImage: cgr.dev/chainguard/static@sha256:fe55470f22d3259488d9d3739168d8f04da67755f0b69382bc26eda4a7d3d327
defaultPlatforms:
  - linux/amd64
  - linux/arm64
builds:
  - main: ./cmd/paco
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -mod=vendor
    ldflags:
      - -s
      - -w
      - -X main.version={{ if index .Env "PACO_VERSION" }}{{ index .Env "PACO_VERSION" }}{{ else }}dev-{{ .Git.ShortCommit }}{{ end }}
      - -X main.commit={{ .Git.FullCommit }}
      - -X main.date={{ .Git.CommitDate }}
